services:
  smanka-school-profile:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smanka-school-profile
    restart: always
    env_file:
      - .env
    environment:
      - PORT=3000
      - NODE_ENV=production
      # Gunakan IP gateway docker default (172.17.0.1) atau localhost host
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@172.17.0.1:5433/${POSTGRES_DB}?schema=public&sslmode=disable&connect_timeout=30
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge